
<script type="text/javascript">

    // console.log("initeasyPack");
    // setTimeout(function () {
    //     window.easyPackAsyncInit = function () {
    //         easyPack.init({
    //             defaultLocale: 'pl',
    //             mapType: 'osm',
    //             searchType: 'osm',
    //             points: {
    //                 types: ['parcel_locker']
    //             },
    //             map: {
    //                 initialTypes: ['parcel_locker']
    //             }
    //         });
    //     };
    //     console.log("initeasyPack 10000");
    // }, 10000);
</script>
<link rel="stylesheet" type="text/css" href="https://geowidget.easypack24.net/css/easypack.css">
